### PR TITLE
Issue 285, Fix the growers.links issue for v2 

### LINKED ISSUE #285: Fix the growers.links issue for v2
There are a few more changes that needed to be made to get the v2 growers.links to work correctly with UUIDs instead of integer ID's

### PR DESCRIPTION
**Pull request by jeremydthomas**
fixes #285 

image
image

the associated org links for growers are currently not used and the species will need to be done eventually. I couldnt find a way to link the planter id to the new uuid grower ids.  This should be enough for me to move on in the front end.

### CODE REVIEW

File: server/models/GrowerAccount.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ function getByName(
 
 function getGrowerAccountLinks(planter) {
   const links = {
-    featured_trees: `/trees?planter_id=${planter.id}&limit=20&offset=0`,
+    featured_trees: `/v2/trees?planter_id=${planter.id}&limit=20&offset=0`,
```
Comment (dadiorchen) [inline server/models/GrowerAccount.ts:54]: @gwynndp is this okay for you?

**Comment by jeremydthomas** [comment]
Can we get an approval here @dadiorchen ? This is where I'm stuck to move forward. The changes shouldn't affect anyone else but me on v2 right?

**Comment by dadiorchen** [comment]
Sorry, @jeremydthomas please solve the confict above and merge this by yourself? 
Because I was driven by the email of notification of github, so I missed this one, next time, feel free to pin me

**Comment by jeremydthomas** [comment]
> Sorry, @jeremydthomas please solve the confict above and merge this by yourself? Because I was driven by the email of notification of github, so I missed this one, next time, feel free to pin me

@dadiorchen Sorry, I didnt think it was right to merge in my own commits.

**Comment by dadiorchen** [comment]
@jeremydthomas can you solve the conflict above?

**Comment by jeremydthomas** [comment]
Yes, I did. Forgot to push it before I left the house, plus I found a different problem with the order_by
